package com.allianz.healthtourism.model.enums;

public enum ProfessionEnum {
    OPHTHALMOLOGY,
    ENT,
    DENTISTRY,
    CARDIOLOGY,
    DERMATOLOGY,
    NEUROLOGY,
    ORTHOPEDICS,
    PEDIATRICS,
    PSYCHIATRY,
    UROLOGY,
    GYNECOLOGY,
    GASTROENTEROLOGY,
    ENDOCRINOLOGY,
    HEMATOLOGY,
    INFECTIOUS_DISEASE,
    NEPHROLOGY,
    ONCOLOGY,
    PULMONOLOGY,
    RHEUMATOLOGY,
    PLASTIC_SURGERY;
}
